name: Task
description: Create a task or work item to be completed
title: "📋[Task]: "
labels: ["task"]
type: task
body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating a task! Please provide details about the work to be done.
  
  - type: textarea
    id: task-description
    attributes:
      label: Task Description
      description: A clear and concise description of the task
      placeholder: Describe what needs to be done
    validations:
      required: true
  
  - type: textarea
    id: objectives
    attributes:
      label: Objectives
      description: What are the goals or objectives of this task?
      placeholder: |
        - Objective 1
        - Objective 2
        - Objective 3
    validations:
      required: true
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the task here
      placeholder: Any additional information that would be helpful
    validations:
      required: false
