name: User Story
description: Create a user story to capture a feature from the user's perspective
title: "[User Story]: "
labels: ["user-story"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating a user story! Please fill out the sections below.
  
  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: As a [role], I want [feature], so that [benefit]
      placeholder: |
        As a [user/admin/developer],
        I want [to perform some action],
        So that [I can achieve some goal]
    validations:
      required: true
  
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this story to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the user story here
      placeholder: Any additional information that would be helpful
    validations:
      required: false
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the priority of this user story?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: false
